version: 0.2

phases:
  install:
    commands:
      - echo Install phase started, updating system
      - sudo apt-get update && sudo apt-get -y upgrade
      - echo Installing Node.js and build essentials
      - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - sudo apt-get install -y build-essential
      - echo Installing Angular
      - npm install -g @angular/cli
      - echo Check Angular version
      - ng -v
      - echo Re-install Angular CLI
      - sudo npm uninstall -g @angular/cli
      - sudo npm cache verify
      - sudo npm install -g @angular/cli --unsafe-perm=true --allow-root
  build:
    commands:
      - ls
      - echo building Angular
      - cd ClientApp      
      - ls
      - ng update @angular/cli
      - ng build --prod
  post_build:
    commands:
      - echo copying files to root
      - mv ClientApp/dist/* ../..