version: 0.2

phases:
  install:
    commands:
      - echo Install phase started, updating system
      - sudo apt-get update && sudo apt-get -y upgrade
      - echo Installing Node.js and build essentials
      - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - sudo apt-get install -y build-essential
      - npm install -g @angular/cli
      - npm install --save-dev @angular-devkit/build-angular
  build:
    commands:
      - ls -a
      - echo building Angular
      - ng build --prod
  post_build:
    commands:
      - ls -a

