version: 0.2

phases:
  install:
    commands:
      - echo Install phase started, updating system
      - sudo apt-get update && sudo apt-get -y upgrade
      - echo Installing Node.js and build essentials
      - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - sudo apt-get install -y build-essential
      - npm install -g @angular/cli
      - npm install --save-dev @angular-devkit/build-angular
  build:
    commands:
      - ng build --prod
      - dotnet restore
      - dotnet publish -c Release
      - ls -a bin/Release/netcoreapp2.0/publish
  post_build:
    commands:
      - cp bin/Release/netcoreapp2.0/publish/* wwwroot
      - ls -a wwwroot
      - cp appspec.yml wwwroot
artifacts:
  files:
    - wwwroot/*
  discard-paths: yes
